#!/bin/sh

VIRTUAL_ENV={virtual_env}
export VIRTUAL_ENV

{ld_library_path}
{ld_preload}

if test "x$VIRTUAL_ENV" != "x"; then
  PATH="$VIRTUAL_ENV/bin:$PATH"
  export PATH
  PYTHONHOME="$VIRTUAL_ENV"
  export PYTHONHOME
fi

cp="{prefix}/lib/jep/jep-{version}.jar"
if test "x$CLASSPATH" != "x"; then
    cp="$cp":"$CLASSPATH"
fi

args=$*
if test "x$args" = "x"; then
  args="{install_lib}jep/console.py"
fi

exec java -classpath "$cp" jep.Run $args
