#!/bin/sh

VIRTUAL_ENV={virtual_env}
export VIRTUAL_ENV

if test "x$VIRTUAL_ENV" != "x"; then
  PATH="$VIRTUAL_ENV/bin:$PATH"
  export PATH
  PYTHONHOME="$VIRTUAL_ENV"
  export PYTHONHOME
fi

if test "x$*" = "x"; then
  exec java -jar {prefix}/lib/jep/jep.jar {install_lib}jep/console.py
else
  exec java -jar {prefix}/lib/jep/jep.jar
fi
