#!/bin/sh

{virtual_env}
{pythonexecutable}
{pythonhome}
{ld_library_path}
{ld_preload}

jep_dir={install_lib}jep

if [ ! -d "$jep_dir" ]
then
    jep_dir={install_lib}{egg_dir}/jep
fi

cp="$jep_dir/jep-{version}.jar"
if test "x$CLASSPATH" != "x"; then
    cp="$cp":"$CLASSPATH"
fi

jni_path=$jep_dir

args=$*
if test "x$args" = "x"; then
  args="$jep_dir/console.py"
fi

exec java -classpath "$cp" -Djava.library.path="$jni_path" jep.Run $args
